name: publish

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: setup:checkout
        uses: actions/checkout@master
      - name: setup:python3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: x64
      - name: deps:install
        shell: bash
        run: |
          yarn
      - name: build:prod
        shell: bash
        run: |
          yarn compile:prod && cd dist
      - name: publish:package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
