name: publish

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: setup:checkout
        uses: actions/checkout@master
      - name: setup:node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: setup:python3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: x64
      - name: deps:install
        shell: bash
        run: |
          yarn
      - name: build:prod
        shell: bash
        run: |
          yarn compile:prod
      - name: publish:package
        run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
